# Version of docker compose
version: "3"

# What we want the docker-compose to do is specified by 'services'-we want it to render
services:
  # 1st service/container
  redis-server:
    # Use 'redis' image to create the 'redis-server'
    image: "redis"
  #   2nd service/container
  node-app:
    # Restart policy
    # restart: always
    # Look in the current directly and use the Dockerfile to build the 'node-app' container
    build: .
    ports:
      # The dash(-) specifies an array
      - "4001:8081"
  # ============RESTART POLICIES=======================
  #1.  "no" - Never attempt to restart this container if it stops or crashes
  #2. "always" - If this container stops for any reason always attempt to restart it
  #3. "on-failure" - Only restart if the container stops with an error code
  #4. "unless-stopped" - Always restart unless we (the developers) forcibly stops it
